# Generated by Django 4.2.20 on 2026-02-21 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('cv_file', models.FileField(blank=True, upload_to='candidates/cvs/', verbose_name='CV (PDF)')),
                ('cv_text_extracted', models.TextField(blank=True, verbose_name='Texto extraído del CV')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('linkedin', 'LinkedIn'), ('email', 'Email'), ('portal', 'Portal')], default='manual', max_length=20, verbose_name='Origen')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('reviewing', 'En revisión'), ('phone_screen', 'Phone screen'), ('interview_scheduled', 'Entrevista programada'), ('interview_done', 'Entrevista realizada'), ('case_sent', 'Case study enviado'), ('case_submitted', 'Case study entregado'), ('evaluation', 'En evaluación'), ('offer_sent', 'Oferta enviada'), ('hired', 'Contratado'), ('rejected', 'Descartado'), ('withdrawn', 'Retirado')], default='new', max_length=25, verbose_name='Estado')),
                ('portal_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token portal')),
                ('portal_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiración del token')),
                ('recruiter_notes', models.TextField(blank=True, verbose_name='Notas del reclutador')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Resumen IA')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Valoración')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='positions.position', verbose_name='Posición')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-created_at'],
            },
        ),
    ]
