# Generated by Django 4.2.20 on 2026-02-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_fit_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Puntuación encaje IA'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_strengths',
            field=models.JSONField(blank=True, default=list, verbose_name='Puntos fuertes IA'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_weaknesses',
            field=models.JSONField(blank=True, default=list, verbose_name='Puntos débiles IA'),
        ),
    ]
