# Generated by Django 4.2.20 on 2026-02-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_ai_fit_score_candidate_ai_strengths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado en'),
        ),
    ]
