# Generated by Django 4.2.20 on 2026-02-21 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('brief_description', models.TextField(verbose_name='Descripción breve')),
                ('full_content', models.TextField(blank=True, verbose_name='Contenido completo')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='Generado con IA')),
                ('deadline_days', models.IntegerField(default=7, verbose_name='Días para entrega')),
                ('evaluation_criteria', models.TextField(blank=True, verbose_name='Criterios de evaluación')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='positions.position', verbose_name='Posición')),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateCaseStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('submission_file', models.FileField(blank=True, upload_to='casestudies/submissions/', verbose_name='Archivo de respuesta')),
                ('submission_text', models.TextField(blank=True, verbose_name='Texto extraído')),
                ('submission_notes', models.TextField(blank=True, verbose_name='Notas del candidato')),
                ('evaluator_notes', models.TextField(blank=True, verbose_name='Notas del evaluador')),
                ('ai_evaluation', models.TextField(blank=True, verbose_name='Evaluación IA')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Puntuación')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='candidates.candidate', verbose_name='Candidato')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='casestudies.casestudy', verbose_name='Case Study')),
            ],
            options={
                'verbose_name': 'Case Study del candidato',
                'verbose_name_plural': 'Case Studies de candidatos',
                'ordering': ['-created_at'],
            },
        ),
    ]
