# Generated by Django 4.2.20 on 2026-03-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='brief_description_ca',
            field=models.TextField(null=True, verbose_name='Descripción breve'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='brief_description_en',
            field=models.TextField(null=True, verbose_name='Descripción breve'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='brief_description_es',
            field=models.TextField(null=True, verbose_name='Descripción breve'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='evaluation_criteria_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Criterios de evaluación'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='evaluation_criteria_en',
            field=models.TextField(blank=True, null=True, verbose_name='Criterios de evaluación'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='evaluation_criteria_es',
            field=models.TextField(blank=True, null=True, verbose_name='Criterios de evaluación'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='full_content_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido completo'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='full_content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido completo'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='full_content_es',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido completo'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='title_ca',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
    ]
