# Generated by Django 4.2.20 on 2026-02-21 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título del puesto')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('employment_type', models.CharField(choices=[('full_time', 'Tiempo completo'), ('part_time', 'Media jornada'), ('freelance', 'Freelance'), ('internship', 'Prácticas')], default='full_time', max_length=20, verbose_name='Tipo de empleo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción del puesto')),
                ('requirements', models.TextField(blank=True, verbose_name='Requisitos')),
                ('about_company_snippet', models.TextField(blank=True, verbose_name='Sobre la empresa')),
                ('salary_range', models.CharField(blank=True, max_length=100, verbose_name='Rango salarial')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('paused', 'Pausada'), ('closed', 'Cerrada')], default='draft', max_length=20, verbose_name='Estado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('has_case_study', models.BooleanField(default=False, verbose_name='Usa case study')),
                ('ai_generated_draft', models.BooleanField(default=False, verbose_name='Borrador generado con IA')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='tenants.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
