# Generated by Django 4.2.20 on 2026-02-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='Qué ofrecemos'),
        ),
    ]
