# Generated by Django 4.2.20 on 2026-02-23 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_data_migrate_profiles_departments'),
        ('positions', '0002_position_benefits'),
    ]

    operations = [
        # Step 1: Rename existing CharField 'department' to 'department_old'
        migrations.RenameField(
            model_name='position',
            old_name='department',
            new_name='department_old',
        ),
        # Step 2: Add new FK field 'department'
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='positions',
                to='tenants.department',
                verbose_name='Departamento',
            ),
        ),
    ]
