# Generated by Django 4.2.20 on 2026-02-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0004_data_link_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='department_old',
        ),
    ]
