# Generated by Django 4.2.20 on 2026-03-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0006_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='about_company_snippet_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre la empresa'),
        ),
        migrations.AddField(
            model_name='position',
            name='about_company_snippet_en',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre la empresa'),
        ),
        migrations.AddField(
            model_name='position',
            name='about_company_snippet_es',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre la empresa'),
        ),
        migrations.AddField(
            model_name='position',
            name='benefits_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Qué ofrecemos'),
        ),
        migrations.AddField(
            model_name='position',
            name='benefits_en',
            field=models.TextField(blank=True, null=True, verbose_name='Qué ofrecemos'),
        ),
        migrations.AddField(
            model_name='position',
            name='benefits_es',
            field=models.TextField(blank=True, null=True, verbose_name='Qué ofrecemos'),
        ),
        migrations.AddField(
            model_name='position',
            name='description_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del puesto'),
        ),
        migrations.AddField(
            model_name='position',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del puesto'),
        ),
        migrations.AddField(
            model_name='position',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del puesto'),
        ),
        migrations.AddField(
            model_name='position',
            name='requirements_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos'),
        ),
        migrations.AddField(
            model_name='position',
            name='requirements_en',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos'),
        ),
        migrations.AddField(
            model_name='position',
            name='requirements_es',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos'),
        ),
        migrations.AddField(
            model_name='position',
            name='salary_range_ca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rango salarial'),
        ),
        migrations.AddField(
            model_name='position',
            name='salary_range_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rango salarial'),
        ),
        migrations.AddField(
            model_name='position',
            name='salary_range_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rango salarial'),
        ),
        migrations.AddField(
            model_name='position',
            name='title_ca',
            field=models.CharField(max_length=200, null=True, verbose_name='Título del puesto'),
        ),
        migrations.AddField(
            model_name='position',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Título del puesto'),
        ),
        migrations.AddField(
            model_name='position',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Título del puesto'),
        ),
    ]
