# Generated by Django 4.2.20 on 2026-03-04 15:39

from django.db import migrations


def create_settings(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserSettings = apps.get_model('core', 'UserSettings')
    for user in User.objects.all():
        UserSettings.objects.get_or_create(user=user, defaults={'language': 'es'})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_settings, migrations.RunPython.noop),
    ]
