# Generated by Django 4.2.20 on 2026-02-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='benefits',
            field=models.TextField(blank=True, help_text='Qué ofrece la empresa a los trabajadores: seguro, formación, fruta, gym...', verbose_name='Beneficios y ventajas'),
        ),
        migrations.AddField(
            model_name='company',
            name='culture',
            field=models.TextField(blank=True, help_text='Valores de la empresa, ambiente de trabajo, equipo...', verbose_name='Cultura y valores'),
        ),
        migrations.AddField(
            model_name='company',
            name='office_location',
            field=models.CharField(blank=True, help_text='Dirección o zona de la oficina principal', max_length=300, verbose_name='Ubicación oficina'),
        ),
        migrations.AddField(
            model_name='company',
            name='remote_policy',
            field=models.CharField(blank=True, help_text='Ej: 100% remoto, híbrido 3 días oficina, presencial...', max_length=200, verbose_name='Política de trabajo remoto'),
        ),
        migrations.AddField(
            model_name='company',
            name='work_schedule',
            field=models.CharField(blank=True, help_text='Ej: L-V 9:00-18:00, jornada flexible...', max_length=200, verbose_name='Jornada laboral'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text='Qué hace la empresa, sector, misión...', verbose_name='Descripción'),
        ),
    ]
