# Generated by Django 4.2.20 on 2026-02-23 06:10

from django.db import migrations


def migrate_profiles_to_memberships(apps, schema_editor):
    """Copy each UserProfile to a CompanyMembership row."""
    UserProfile = apps.get_model('tenants', 'UserProfile')
    CompanyMembership = apps.get_model('tenants', 'CompanyMembership')

    for profile in UserProfile.objects.select_related('user', 'company').all():
        CompanyMembership.objects.get_or_create(
            user=profile.user,
            company=profile.company,
            defaults={'role': profile.role},
        )


def extract_departments(apps, schema_editor):
    """Extract unique department names from Position.department CharField into Department rows."""
    Position = apps.get_model('positions', 'Position')
    Department = apps.get_model('tenants', 'Department')

    # Get unique (company_id, department) pairs where department is not empty
    seen = set()
    for pos in Position.objects.exclude(department='').select_related('company'):
        key = (pos.company_id, pos.department.strip())
        if key not in seen and key[1]:
            seen.add(key)
            Department.objects.get_or_create(
                company=pos.company,
                name=pos.department.strip(),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_create_companymembership_department'),
        ('positions', '0002_position_benefits'),
    ]

    operations = [
        migrations.RunPython(
            migrate_profiles_to_memberships,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            extract_departments,
            migrations.RunPython.noop,
        ),
    ]
