# Generated by Django 4.2.20 on 2026-02-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_data_migrate_profiles_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado en'),
        ),
    ]
