# Generated by Django 4.2.20 on 2026-03-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='benefits_ca',
            field=models.TextField(blank=True, help_text='Qué ofrece la empresa a los trabajadores: seguro, formación, fruta, gym...', null=True, verbose_name='Beneficios y ventajas'),
        ),
        migrations.AddField(
            model_name='company',
            name='benefits_en',
            field=models.TextField(blank=True, help_text='Qué ofrece la empresa a los trabajadores: seguro, formación, fruta, gym...', null=True, verbose_name='Beneficios y ventajas'),
        ),
        migrations.AddField(
            model_name='company',
            name='benefits_es',
            field=models.TextField(blank=True, help_text='Qué ofrece la empresa a los trabajadores: seguro, formación, fruta, gym...', null=True, verbose_name='Beneficios y ventajas'),
        ),
        migrations.AddField(
            model_name='company',
            name='culture_ca',
            field=models.TextField(blank=True, help_text='Valores de la empresa, ambiente de trabajo, equipo...', null=True, verbose_name='Cultura y valores'),
        ),
        migrations.AddField(
            model_name='company',
            name='culture_en',
            field=models.TextField(blank=True, help_text='Valores de la empresa, ambiente de trabajo, equipo...', null=True, verbose_name='Cultura y valores'),
        ),
        migrations.AddField(
            model_name='company',
            name='culture_es',
            field=models.TextField(blank=True, help_text='Valores de la empresa, ambiente de trabajo, equipo...', null=True, verbose_name='Cultura y valores'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_ca',
            field=models.TextField(blank=True, help_text='Qué hace la empresa, sector, misión...', null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_en',
            field=models.TextField(blank=True, help_text='Qué hace la empresa, sector, misión...', null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_es',
            field=models.TextField(blank=True, help_text='Qué hace la empresa, sector, misión...', null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_ca',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='company',
            name='office_location_ca',
            field=models.CharField(blank=True, help_text='Dirección o zona de la oficina principal', max_length=300, null=True, verbose_name='Ubicación oficina'),
        ),
        migrations.AddField(
            model_name='company',
            name='office_location_en',
            field=models.CharField(blank=True, help_text='Dirección o zona de la oficina principal', max_length=300, null=True, verbose_name='Ubicación oficina'),
        ),
        migrations.AddField(
            model_name='company',
            name='office_location_es',
            field=models.CharField(blank=True, help_text='Dirección o zona de la oficina principal', max_length=300, null=True, verbose_name='Ubicación oficina'),
        ),
        migrations.AddField(
            model_name='company',
            name='remote_policy_ca',
            field=models.CharField(blank=True, help_text='Ej: 100% remoto, híbrido 3 días oficina, presencial...', max_length=200, null=True, verbose_name='Política de trabajo remoto'),
        ),
        migrations.AddField(
            model_name='company',
            name='remote_policy_en',
            field=models.CharField(blank=True, help_text='Ej: 100% remoto, híbrido 3 días oficina, presencial...', max_length=200, null=True, verbose_name='Política de trabajo remoto'),
        ),
        migrations.AddField(
            model_name='company',
            name='remote_policy_es',
            field=models.CharField(blank=True, help_text='Ej: 100% remoto, híbrido 3 días oficina, presencial...', max_length=200, null=True, verbose_name='Política de trabajo remoto'),
        ),
        migrations.AddField(
            model_name='company',
            name='work_schedule_ca',
            field=models.CharField(blank=True, help_text='Ej: L-V 9:00-18:00, jornada flexible...', max_length=200, null=True, verbose_name='Jornada laboral'),
        ),
        migrations.AddField(
            model_name='company',
            name='work_schedule_en',
            field=models.CharField(blank=True, help_text='Ej: L-V 9:00-18:00, jornada flexible...', max_length=200, null=True, verbose_name='Jornada laboral'),
        ),
        migrations.AddField(
            model_name='company',
            name='work_schedule_es',
            field=models.CharField(blank=True, help_text='Ej: L-V 9:00-18:00, jornada flexible...', max_length=200, null=True, verbose_name='Jornada laboral'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
