# Generated by Django 4.2.20 on 2026-02-21 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('prompt_used', models.TextField(verbose_name='Prompt enviado')),
                ('result', models.TextField(verbose_name='Respuesta completa de Claude')),
                ('cv_score', models.IntegerField(blank=True, null=True, verbose_name='Puntuación CV')),
                ('interview_score', models.IntegerField(blank=True, null=True, verbose_name='Puntuación entrevista')),
                ('case_score', models.IntegerField(blank=True, null=True, verbose_name='Puntuación case study')),
                ('overall_score', models.IntegerField(blank=True, null=True, verbose_name='Puntuación final')),
                ('recommendation', models.CharField(blank=True, choices=[('hire', 'Contratar'), ('hold', 'En espera'), ('reject', 'Rechazar')], max_length=10, verbose_name='Recomendación')),
                ('summary', models.TextField(blank=True, verbose_name='Resumen ejecutivo')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='candidates.candidate', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Evaluación IA',
                'verbose_name_plural': 'Evaluaciones IA',
                'ordering': ['-generated_at'],
            },
        ),
    ]
