# Generated by Django 4.2.20 on 2026-02-21 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(verbose_name='Fecha y hora')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Duración (minutos)')),
                ('location_or_link', models.CharField(blank=True, max_length=500, verbose_name='Lugar o link')),
                ('google_event_id', models.CharField(blank=True, max_length=200, verbose_name='ID evento Google Calendar')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('completed', 'Realizada'), ('cancelled', 'Cancelada'), ('no_show', 'No se presentó')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('strengths', models.TextField(blank=True, verbose_name='Puntos fuertes')),
                ('weaknesses', models.TextField(blank=True, verbose_name='Puntos débiles')),
                ('overall_score', models.IntegerField(blank=True, null=True, verbose_name='Puntuación global')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidates.candidate', verbose_name='Candidato')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_as_interviewer', to=settings.AUTH_USER_MODEL, verbose_name='Entrevistador')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
