# Generated by Django 4.2.20 on 2026-02-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('candidate_new', 'Nuevo candidato'), ('status_change', 'Cambio de estado'), ('interview', 'Entrevista'), ('case_study', 'Caso práctico'), ('evaluation', 'Evaluación'), ('position', 'Posición'), ('info', 'Información'), ('system', 'Sistema')], default='info', max_length=30, verbose_name='Tipo'),
        ),
    ]
